services:
  # mysql 설정
  churai-mysql:
    image: 'mysql:8.0'
    container_name: churai-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      TZ: Asia/Seoul
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - churai-network

  # Nginx
  churai-nginx:
    image: nginx:stable-alpine
    container_name: churai-nginx
    restart: always
    depends_on:
      - churai-app
    networks:
      - churai-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  churai-app:
    image: ${DOCKER_USERNAME}/churai-be:latest
    container_name: churai-be
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://churai-mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  
    depends_on:
      - churai-mysql
    networks:
      - churai-network

# 각 서비스들이 서로 통신할 수 있는 가상의 네트워크 정의
networks:
  churai-network:
    driver: bridge

# 데이터 보존을 위한 명명된 볼륨 정의
volumes:
  mysql_data:
