spring:
  application:
    name: CHURAI-BE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/churai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:churai1629@}
    password: ${SPRING_DATASOURCE_PASSWORD:churai1629@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Asia/Seoul

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      session-token: ${AWS_SESSION_TOKEN:}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    stack:
      auto: false

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    org.hibernate.SQL: debug
